// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMKx8g-A1By6pSUgdfes_QliLwWN-6iZ8',
    appId: '1:918510273238:web:35750688869498f9d0bf77',
    messagingSenderId: '918510273238',
    projectId: 'cosc499-9a063',
    authDomain: 'cosc499-9a063.firebaseapp.com',
    storageBucket: 'cosc499-9a063.appspot.com',
    measurementId: 'G-K099F2V94L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4nmpFKUDgUts536vHEIsh4OXv2nhGtGc',
    appId: '1:918510273238:android:f6eac14df961ad48d0bf77',
    messagingSenderId: '918510273238',
    projectId: 'cosc499-9a063',
    storageBucket: 'cosc499-9a063.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRW6xQUljxL_JWLceOnPJBT9v69hqYvHI',
    appId: '1:918510273238:ios:2732b86222888c04d0bf77',
    messagingSenderId: '918510273238',
    projectId: 'cosc499-9a063',
    storageBucket: 'cosc499-9a063.appspot.com',
    iosBundleId: 'com.example.foodhood2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRW6xQUljxL_JWLceOnPJBT9v69hqYvHI',
    appId: '1:918510273238:ios:5a059b92ec39315ad0bf77',
    messagingSenderId: '918510273238',
    projectId: 'cosc499-9a063',
    storageBucket: 'cosc499-9a063.appspot.com',
    iosBundleId: 'com.example.foodhood2.RunnerTests',
  );
}
